### ISSUE TITLE
The `IFlashMintReceiver` callback should take a `sender` parameter.

### ISSUE THREAD

**Issue by alcueca** [makerdao/dss-flash#11]
The receiver will always be a contract that needs to know the user that originated the transaction, and only flash.sol can safely say who that is. The callback interface should include a sender parameter, filled by `flash.mint` with `msg.sender`.

`IFlashMintReceiver(_receiver).onFlashMint(msg.sender, _amount, fee, _data);`

Leaving to the sender to fill data with the account to manipulate on the callback would be unsafe.

There are other mechanisms to safely pass the target account, if sender would not be an EOA. Namely you can either store the address of the target account in a state variable in the receiver, or use off-chain signatures embedded in data. Both methods are more complex and expensive than just having flash.sol state who is the sender.

An implementation of this proposed standard interface, with tests, can be found in [WETH10](https://github.com/WETH10/WETH10/pull/81).

**Comment by hexonaut** [comment]
This makes sense to me. I'll open a PR for this change shortly.
