### ISSUE TITLE
Consider optimizing storage usage in mint

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/dss-flash#13]
There is actually not need to check `vat.dai(address(this))`.
Just the execution of `vat.heal` and `vat.move` ensures there was enough DAI paid back to balance out the debt of the module + paying the fee.

The only consequence is any DAI sent to this module directly can then be used by anyone in a flash loan (effectively having to return less DAI), but honestly I don't see that as a bad thing, it is just better that leaving it locked there.

**Comment by gbalabasquer** [comment]
Basically these lines could go:
```
uint256 bal = vat.dai(address(this));
```
```
require(vat.dai(address(this)) == add(bal, add(arad, frad)), "DssFlash/invalid-payback");
```

**Comment by hexonaut** [comment]
I like this change. First and foremost it saves `7674` gas with the added benefit of being able to clear out locked Dai.
