### ISSUE TITLE
Use single store reentrancy guard

### ISSUE THREAD

**Issue by hexonaut** [makerdao/dss-flash#5]
Switching locked from 1 to 2 and back again causes two SSTORE operations which is expensive. Instead we can use this implementation which achieves the same result with one less store:

    contract ReentrancyGuard {
        /// @dev counter to allow mutex lock with only one SSTORE operation
        uint256 private _guardCounter;

        constructor () internal {
            // The counter starts at one to prevent changing it from zero to a non-zero
            // value, which is a more expensive operation.
            _guardCounter = 1;
        }

        /**
         * @dev Prevents a contract from calling itself, directly or indirectly.
         * Calling a `nonReentrant` function from another `nonReentrant`
         * function is not supported. It is possible to prevent this from happening
         * by making the `nonReentrant` function external, and make it call a
         * `private` function that does the actual work.
         */
        modifier nonReentrant() {
            _guardCounter += 1;
            uint256 localCounter = _guardCounter;
            _;
            require(localCounter == _guardCounter, "ReentrancyGuard: reentrant call");
        }
    }

**Comment by desp4c1t0** [comment]
Excellent!
But will that cause Dos (Deny of service attack), I mean this modifier always reverts previous ones, and only the final one would succeed. What if there are calls keeping coming and no final one? So the function will keep reverting and do nothing.
I am new to Blockchain, so I am really confused about it.

**Comment by hexonaut** [comment]
Re-opening this as it appears refunds may be on the way out: https://eips.ethereum.org/EIPS/eip-3298

It may be better to use the single SSTORE version in anticipation of this EIP being merged in the near future.

**Comment by desp4c1t0** [comment]
I get your point now. What a nice idea! Thanks.

**Comment by hexonaut** [comment]
Nevermind. EIP-3298 will actually make zero -> nonzero -> zero storage cheaper.
