### ISSUE TITLE
Change lock values

### ISSUE THREAD

**Issue by hexonaut** [makerdao/dss-flash#9]
Open Zeppelin Reentrancy Gaurd is using 1 and 2 for the values to switch between instead of 0 and 1: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/ReentrancyGuard.sol

Need to run a gas test to see if this saves gas.

**Comment by gbalabasquer** [comment]
As far as I remember, it used to save gas before some hard fork which changed the storage usage gas costs. I think they should cost the same now.

**Comment by hexonaut** [comment]
I'll run a quick test none-the-less. If it's the same or worse, I won't touch it.

**Comment by hexonaut** [comment]
Running a quick test I see gas savings of `19200` by using 1 and 2 instead of 0 and 1. This is pretty significant imo. I'm going to open a PR to make this change.
